---
# Task adapted for using with Centos 6 and 7

#- name: Stopping Firewalld...
#  service: name=firewalld state=stopped enabled=no
#  ignore_errors: false
#  when:
#  - ansible_distribution == "CentOS"
#  - ansible_distribution_major_version == "7"

- name: Installing iptables-services...
  yum:
    name: iptables-services
    state: present
    update_cache: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Reload systemd
  systemd:
    daemon_reload: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Installing iptables rules...
  template:
    src: "{{ firewall_profile | default('common') }}.iptables"
    dest: /etc/sysconfig/iptables
    backup: true
  notify: restore iptables

- name: Starting iptables...
  service:
    name: iptables
    enabled: true
    state: started

- meta: flush_handlers
