---
- name: Check ntpd enabled CentOS...
  service: name=ntpd state=started enabled=yes
  when: ansible_os_family == "RedHat" and ansible_service_mgr != "systemd"

- name: Check ntpd enabled Debian...
  service: name=ntp state=started enabled=yes
  when: ansible_os_family == "Debian" and ansible_service_mgr != "systemd"

- name: Starting ntpd via SystemD
  systemd: name=ntpd enabled=yes state=restarted daemon_reload=yes
  when: ansible_os_family == "RedHat" and ansible_service_mgr == "systemd"

- name: Starting ntpd via SystemD
  systemd: name=ntp enabled=yes state=started daemon_reload=yes
  when: ansible_os_family == "Debian" and ansible_service_mgr == "systemd"

- meta: flush_handlers
