---
- name: Creating sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    state: "{{ item.state | default('present') }}"
  with_items: "{{ sysctl_settings }}"
