pipeline {
    agent { label 'lxc' }
    options {
        checkoutToSubdirectory('common')
    }
    stages {
        stage('Test') {
            steps {
                dir('common') {
                    sh 'molecule test'
                }
            }
        }
    }
}
